name: build

on:
  push:

  workflow_dispatch:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build
        run: gatsby build
      
      - name: Verify build
        run: ls -la public

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/trunk' }}
          tags: |
            ghcr.io/phillipleblanc/leblanc.tech:latest
            ghcr.io/phillipleblanc/leblanc.tech:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
